# yosys2simcirjs
This package is (currently) a prototype for exporting netlists
generated by the synthesis software Yosys to an usable circuit
simulator. SimcirJS was used because of its simplicity and
support for hierarchical designs.
